name: .NET Core Manual

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow   
  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
          versionSpec: '5.5.0'
    
    - name: Determine version
      uses: gittools/actions/gitversion/execute@v0.9.11
       
    - name: Display version
      run: |
       echo "SemVer: $GITVERSION_SEMVER"
       
    - name: Install dependencies
      run: dotnet restore
    - name: Build ${{ env.GitVersion_SemVer }}
      run: dotnet build --configuration Release --no-restore /p:AssemblyVersion=$GITVERSION_SEMVER /p:FileVersion=$GITVERSION_ASSEMBLYSEMFILEVER  /p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v1
      continue-on-error: true
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: ${{ toJSON(job) }}
